name: Docker Image (latest) CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:

  dockerimage-latest:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      #      - name: Remove builder
      #        if: always()
      #        run: docker buildx rm builder || true

      #      - name: Available platforms
      #        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Buildx and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag ${DOCKER_USERNAME}/fava:latest

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
