name: Docker Image (release) CI

on:
  push:
    tags: [ '*' ]

jobs:

  dockerimage-release:

    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/get-version
      - name: Retrieve version from git tag
        id: get_version
        uses: battila7/get-version-action@v2

      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          build-args: VERSION=${{ steps.get_version.outputs.version-without-v }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fava:${{ steps.get_version.outputs.version-without-v }}

      # https://github.com/rtCamp/action-slack-notify
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
